### ISSUE TITLE
Functions for arbitrary-dimension arrays

### ISSUE THREAD

**Issue by mkborregaard** [mlubin/NaNMath.jl#19]
These functions are also often applied to e.g. `Matrix{<:AbstractFloat}` with `NaN`s, but currently there are only defined methods for `Vector`s. Are there plans to make them general? 
I guess it could be done with `@generated` functions using `@nloops`/`@nref`?

**Comment by mkborregaard** [comment]
Or possibly just changing the type signature to `AbstractArray` is enough.

**Comment by mkborregaard** [comment]
@dpsanders suggested that here. https://github.com/JuliaPlots/Plots.jl/issues/796#issuecomment-303979785 .
Would you take a PR doing that?

**Comment by mkborregaard** [comment]
Bump - any feedback on the idea of replacing `Vector` with `AbstractArray` in the container-passing functions?

**Comment by mlubin** [comment]
Fine with me

**Comment by mkborregaard** [comment]
Great! https://github.com/mlubin/NaNMath.jl/pull/20
