### ISSUE TITLE
WARNING: both NaNMath and Base export "log"; uses of it in module Main must be qualified

### ISSUE THREAD

**Issue by gizemk** [mlubin/NaNMath.jl#23]
I'm using the NaNMath package to use the mean and the standard deviation functions but after I write 
using NaNMath; nm = NaNMath
I'm first getting a warning that says "WARNING: using NaNMath.log in module Main conflicts with an existing identifier." and then when I try to use the log function (the usual log function from the Base) it gives an error saying log not defined. 
How can I fix this issue?
Thanks!

**Comment by mlubin** [comment]
That's strange because NaNMath does not export anything at all. Try restarting your julia session.

**Comment by gizemk** [comment]
I've restarted it several times. I get the same error even when I import NaNMath. 
I don't experience the same issue when I use another computer. On my laptop, I use:
![screen shot 2017-09-13 at 6 56 56 pm](https://user-images.githubusercontent.com/12506703/30404597-6549b8a2-98b5-11e7-9332-429cd5dfa334.png)
Any ideas?

**Comment by mlubin** [comment]
Closing as this appears to be a stale issue.
