### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by juliohm** [mlubin/NaNMath.jl#34]
Reporting as suggested by the error message:

![Screen Shot 2019-11-20 at 20 04 22](https://user-images.githubusercontent.com/3345261/69286084-18c73400-0bd1-11ea-8b79-869bf5923385.png)

**Comment by mlubin** [comment]
Unless I'm missing something obvious, `Compat` is not used anywhere in the latest release of `NaNMath`, so it shouldn't be listed as a dependency. It was used in the previous release.

I don't think there's anything to be fixed here, seems like an issue somewhere else. Discourse is a better forum for support.

**Comment by juliohm** [comment]
Oh so this is an old release that is probably stuck because of another package. I will close the issue here, thanks.
