### ISSUE TITLE
StackOverflowError for pow(::Float32, ::Float64)

### ISSUE THREAD

**Issue by torfjelde** [mlubin/NaNMath.jl#47]
`pow(::Float32, ::Float64)` results in a StackOverflowError due to the use of `float` in the default implementation:
https://github.com/mlubin/NaNMath.jl/blob/0fc4df8442fcefebe8efe490781fce5663c03b02/src/NaNMath.jl#L23-L25

Maybe there ought to be a `promote` here?

**Comment by mlubin** [comment]
That could work, feel free to open a PR.

**Comment by mlubin** [comment]
Closed by https://github.com/mlubin/NaNMath.jl/pull/50 and tagged a new release
