### ISSUE TITLE
Glib_jll downgrade

### ISSUE THREAD

**Issue by ptoche** [mlubin/NaNMath.jl#48]
I just wanted to point out that `Pkg.add("NaNMath")` induces a downgrade of `Glib_jll`from `v2.68` to `v2.59`, which was released only 6 days ago. Probably not a big deal, but thought I'd mention it.

<img width="467" alt="a" src="https://user-images.githubusercontent.com/6339274/119775793-f292ec00-be78-11eb-8845-ae421479d80f.png">

**Comment by mlubin** [comment]
Thanks for the pointer, but I don't think this is actionable or even related to NaNMath. NaNMath has literally [no dependencies](https://github.com/mlubin/NaNMath.jl/blob/0fc4df8442fcefebe8efe490781fce5663c03b02/Project.toml#L7).

**Comment by ptoche** [comment]
Oh sorry.  `Pkg.add("NaNMath")` triggered this. I find `Pkg` quite difficult to understand at times. It often downgrades packages. I wonder what would make `Pkg` think: "I'm adding this new package, I might as well do other unrelated stuff while I'm at it".  🤣
