### ISSUE TITLE
Tag version 0.03 (or 0.1?)

### ISSUE THREAD

**Issue by ufechner7** [mlubin/NaNMath.jl#6]
It would be nice to tag a new version to make the added fuctions available for normal users.

**Comment by ufechner7** [comment]
In addition, it would be nice to modify the package description, for example to: Julia math built-ins which return NaN and vector functions that ignore NaN's.

**Comment by mlubin** [comment]
@ufechner7, you should have commit access now. Feel free to tag 0.1. Please continue to use PRs for any large changes.
